### ISSUE TITLE
Cronograma

### ISSUE THREAD

**Issue by Gabrielle-Ribeiro** [Interacao-Humano-Computador/2020.1-Prefeitura-Municipal-de-Arco-Iris#13]
**Descrição**

Realizar alterações no cronograma do planejamento.

**Tasks**

- [x] Detalhar mais o cronograma.

**Informações Adicionais**

Não esquecer de subir o cronograma com uma resolução melhor.

**Comment by giovannabbottino** [comment]
Adicionado novo cronograma e feito o PR
